---
- name: Install hostfile
  become: true
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: '0644'
    backup: true
- name: Copy private ssh and config
  copy:
    src: ssh/
    dest: .ssh
    mode: '0600'
- name: Enable ssh keys
  authorized_key:
    user: vagrant
    key: '{{ item }}'
    state: present
  with_file:
    - ssh/id_rsa.pub
- name: Install containerd
  become: true
  copy:
    src: containerd/
    dest: /usr/bin
    mode: '0755'
    owner: root
    group: root
- name: Install libseccomp2
  become: true
  apt:
    name: libseccomp2
    state: present
- name: Copy konk binary
  become: true
  copy:
    src: konk
    dest: /usr/bin/konk
    mode: '0755'
- name: Copy konk config
  become: true
  copy:
    src: konk-ip.yaml
    dest: /etc/konk.yaml
    mode: '0644'
- name: Deploy systemd services
  become: true
  copy:
    src: systemd/
    dest: /lib/systemd/system/
    owner: root
    group: root
- name: Start containerd
  become: true
  systemd:
    state: started
    daemon_reload: yes
    name: containerd

